import { EZStreamButton, EZStreamTextButton } from "components/primitive/EZStreamButton.slint";

import { EZStreamTextInput } from "components/primitive/EZStreamTextInput.slint";

import "./res/Figtree_VariableFont_wght.ttf";

import { EZStreamWindowPreferences as WP } from "WindowPreferences.slint";
import { EZStreamScoreInput } from "components/EZStreamScoreInput.slint";
import { CenteredGridLayout } from "components/primitive/CenteredGridLayout.slint";

export component MainWindow inherits Window {
    title: "EZ-Stream";
    width: 600px;
    height: 300px;

    callback player-1-tag-changed(new-text: string);
    callback player-2-tag-changed(new-text: string);
    callback player-1-score-changed(new-score: int);
    callback player-2-score-changed(new-score: int);

    background: WP.color-scheme.background-color;

    CenteredGridLayout {
        vertical-spacing: 3px;

        // ---- TOP ROW ---- //

        HorizontalLayout {
            alignment: center;
            row: 2;
            col: 0;
        
            EZStreamTextInput {
                placeholder-text: "Player 1 Tag";
                font-size: WP.font-size;
                width: 200px;
                height: 20px;
                text-changed(new-text) => player-1-tag-changed(new-text);
            }
        }

        HorizontalLayout {
            alignment: center;
            row: 2;
            col: 2;

            EZStreamTextInput {
                placeholder-text: "Player 2 Tag";
                font-size: WP.font-size;
                width: 200px;
                height: 20px;
                text-changed(new-text) => player-2-tag-changed(new-text);
            }
        }


        // ---- SECOND ROW ---- //

        HorizontalLayout {
            row: 3;
            col: 0;
            alignment: center;
        
            EZStreamScoreInput {
                score-changed(new-score) => { player-1-score-changed(new-score); }
            }
        }

        HorizontalLayout {
            row: 3;
            col: 2;
            alignment: center;

            EZStreamScoreInput {
                score-changed(new-score) => { player-2-score-changed(new-score); }
            }
        }

        // ---- BOTTOM ROW ---- //

        HorizontalLayout {
            row: 9;
            col: 1;
            alignment: center;

            EZStreamTextButton {
                width: 150px;
                height: 50px;
                label: "UPDATE";
            }
        }
    }
}
