import {
    EZStreamButton,
    EZStreamTextButton,
} from "components/primitive/EZStreamButton.slint";

import {
    EZStreamTextInput,
} from "components/primitive/EZStreamTextInput.slint";

import "./res/Figtree_VariableFont_wght.ttf";

import { EZStreamWindowPreferences as WP } from "WindowPreferences.slint";
import { EZStreamScoreInput } from "components/EZStreamScoreInput.slint";

export component MainWindow inherits Window {
    title: "EZ-Stream";
    width: 600px;
    height: 300px;

    callback player-1-tag-changed(new-text: string);
    callback player-2-tag-changed(new-text: string);

    background: WP.color-scheme.background-color;

    VerticalLayout {
        spacing: 10px;
        alignment: center;

        HorizontalLayout {

            alignment: LayoutAlignment.space-evenly;

            EZStreamTextInput {
                placeholder-text: "Player 1 Tag";
                font-size: WP.font-size;
                width: 200px;
                height: 20px;
                text-changed(new-text) => player-1-tag-changed(new-text);
            }

            EZStreamTextInput {
                placeholder-text: "Player 2 Tag";
                font-size: WP.font-size;
                width: 200px;
                height: 20px;
                text-changed(new-text) => player-2-tag-changed(new-text);
            }
        }

        HorizontalLayout {
            alignment: center;

            EZStreamScoreInput { }
        }
    }
}
